update the docs of Subreddit's attributes
praw-dev/asyncpraw pull request #190
Opened 2022-06-15 03:37 UTC by kaif-00z

Fixes # (provide issue number if applicable)

## Feature Summary and Justification

This pull request provides ...

## References

-

2022-06-15 03:38 UTC, LilSpazJoekp commented
Please fill out the pull request description.

2022-06-15 06:31 UTC, kaif-00z commented
> Please fill out the pull request description.

🤦‍♂️ done

2022-06-17 21:46 UTC, LilSpazJoekp requested changes
Minor change.

Would you add this to `asyncpraw/models/reddit/user_subreddit.py` as well.

2022-06-17 21:46 UTC, LilSpazJoekp commented on asyncpraw/models/reddit/subreddit.py
> +    ``icon_img``              The url of the Subreddit's icon.
```suggestion
    ``icon_img``              The URL of the subreddit icon image.
```
Let's word it like this.

2022-06-18 05:27 UTC, kaif-00z commented
> Minor change.
> 
> Would you add this to `asyncpraw/models/reddit/user_subreddit.py` as well.

done

2022-06-21 14:57 UTC, LilSpazJoekp approved these changes

2022-06-21 14:58 UTC, merged

2022-06-21 14:58 UTC, LilSpazJoekp commented
Thank you!