Change stream cache eviction to least-recently-used
praw-dev/asyncpraw pull request #20
Opened 2020-11-28 21:19 UTC by leviroth

This is the same patch as https://github.com/praw-dev/praw/pull/1547, but applied to the equivalent files in Async PRAW.

I haven't made any effort to test beyond importing the unit test patch, nor do I know anything about Async PRAW beyond some general knowledge of asyncio.

2020-11-28 22:25 UTC, PythonCoderAS requested changes
A few changes to be made in order to make the test async-compliant. I had to use an external counter since I am not aware of a next() function for async generators.

2020-11-28 22:25 UTC, PythonCoderAS commented on tests/unit/models/test_util.py
> +    def test_stream(self, _):
```suggestion
    async def test_stream(self, _):
```

2020-11-28 22:25 UTC, PythonCoderAS commented on tests/unit/models/test_util.py
> +        def generate(limit, **kwargs):
```suggestion
        async def generate(limit, **kwargs):
```

2020-11-28 22:25 UTC, PythonCoderAS commented on tests/unit/models/test_util.py
> +            seen.add(thing)
```suggestion
        loop_counter = 0
        async for thing in stream:
            assert thing not in seen
            seen.add(thing)
            counter += 1
            if counter == 400:
                break
```

2020-11-28 22:30 UTC, PythonCoderAS commented
Upon further review, it seems that a custom async iterator is going to have to replace the function.

2020-11-28 23:11 UTC, LilSpazJoekp commented
> Upon further review, it seems that a custom async iterator is going to have to replace the function.

I have helper functions made here: https://github.com/praw-dev/asyncpraw/blob/ad443d6a9218e8868dfcd33d53ae9fd3508c9ce7/tests/integration/__init__.py#L76-L85

Note that `async_next()` is not a true implementation of `next()`. I think using `async_list()` to convert it to a list would be best as you can then you can use `next()`.

2020-11-28 23:25 UTC, PythonCoderAS commented
I think the issue here is that in normal PRAW, the function returns a normal iterator (a list). The function therefore should logically return an async iterator. The best idea would be an async list, which inherits from list, and the `__anext__` method should yield the list's attributes back.

2020-12-12 19:58 UTC, leviroth commented
As a heads up, I'm not planning to work on this patch any further. Feel free to do whatever you like with it.

2020-12-13 07:23 UTC, merged